# Generated by Django 3.1.3 on 2020-12-01 07:25

from django.db import migrations
import pyuploadcare.dj.models


class Migration(migrations.Migration):

    dependencies = [
        ('award', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='photo',
            field=pyuploadcare.dj.models.ImageField(blank=True, verbose_name=''),
        ),
    ]
