# Generated by Django 3.1.3 on 2020-12-01 15:09

from django.db import migrations
import pyuploadcare.dj.models


class Migration(migrations.Migration):

    dependencies = [
        ('award', '0002_post_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='photo',
            field=pyuploadcare.dj.models.ImageField(blank=True),
        ),
    ]
